export const PORT_QUESTIONS = [
  { port: 20, description: "FTP data transfer" },
  { port: 21, description: "FTP control (command)" },
  { port: 22, description: "SSH - Secure Shell" },
  { port: 23, description: "Telnet (unsecured remote login)" },
  { port: 25, description: "SMTP - Simple Mail Transfer Protocol" },
  { port: 53, description: "DNS - Domain Name System" },
  { port: 67, description: "DHCP server" },
  { port: 68, description: "DHCP client" },
  { port: 80, description: "HTTP - web traffic" },
  { port: 110, description: "POP3 - Post Office Protocol" },
  { port: 143, description: "IMAP - Internet Message Access Protocol" },
  { port: 161, description: "SNMP - Simple Network Management Protocol" },
  { port: 443, description: "HTTPS - secure web traffic" },
  { port: 465, description: "SMTPS - SMTP over SSL" },
  { port: 587, description: "Submission (mail submission over TLS)" },
  { port: 993, description: "IMAPS - IMAP over SSL" },
  { port: 995, description: "POP3S - POP3 over SSL" },
];
